kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - npm i
      - npm run build

  - name: deploy
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
    settings:
      user: root
      hosts:
      - cu.laoz.org
      port: 13223
      source: ./public
      target: /root/env/blog
      delete: true

trigger:
  event:
  - push