kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - npm i
      - npm run build

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: npm.laoz.org
      username: root
      password: 
        from_secret: psw
      port: 10086
      target: /root/env/npm/data
      source: ./public

  - name: finish
    image: curlimages/curl
    commands:
      - /bin/sh bark.sh

trigger:
  event:
  - push