kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - npm i
      - npm run build

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: cu.laoz.org
      username: root
      password: 
        from_secret: psw
      port: 13223
      target: /root/env/blog
      source: ./public

trigger:
  event:
  - push